version: 2.1
orbs:
  node: circleci/node@4.7

  jobs:
    cicd-job:
      executor:
        name: node/default
      steps:
        - checkout
        - run: npm install
        - run: npm rebuild
        - run: npm test

  workflows:
    example-workflow:
      jobs:
        - cicd-job
