version: 2.1
orbs:
  node: circleci/node@4.7

  jobs:
    test:
      executor: node/default
      steps:
        - checkout
        - run: npm install
        - run: npm rebuild
        - run: npm test

  workflows:
    my-workflow:
      jobs:
        - test


